# Generated by Django 6.0.4 on 2026-04-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_planningblock_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='Вес задачи для расчета прогресса'),
        ),
    ]
