# Generated by Django 6.0.4 on 2026-04-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_task_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningblock',
            name='avg_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Средняя длительность в днях', null=True),
        ),
        migrations.AddField(
            model_name='planningblock',
            name='complexity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='planningblock',
            name='success_rate',
            field=models.FloatField(default=1.0, help_text='Показатель успешности (0.0 - 1.0)'),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('AT_RISK', 'At Risk'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
