# Generated by Django 6.0.4 on 2026-04-29 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('projects', '0004_planningblock_avg_duration_planningblock_complexity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningblock',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='plans.workcalendar'),
        ),
        migrations.AddField(
            model_name='planningblock',
            name='typical_risks',
            field=models.ManyToManyField(blank=True, related_name='typical_in_blocks', to='plans.risk'),
        ),
        migrations.AddField(
            model_name='project',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='plans.workcalendar'),
        ),
    ]
