# Generated by Django 6.0.4 on 2026-04-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_planningblock_calendar_planningblock_typical_risks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='allocation_percentage',
            field=models.IntegerField(default=100, help_text='Процент занятости в этом проекте'),
        ),
    ]
