# Generated by Django 6.0.4 on 2026-04-29 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectmember_allocation_percentage'),
        ('workflows', '0003_workflowtask_estimated_hours_workflowtask_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningblock',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planningblock',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.planningblock'),
        ),
        migrations.AddField(
            model_name='planningblock',
            name='process_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_blocks', to='workflows.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='process_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_tasks', to='workflows.workflowtemplate'),
        ),
    ]
