# Generated by Django 6.0.4 on 2026-04-29 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_task_parent'),
        ('workflows', '0003_workflowtask_estimated_hours_workflowtask_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='dependent_tasks', to='projects.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='workflow_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbs_task', to='workflows.workflowtask'),
        ),
    ]
