# Generated by Django 6.0.4 on 2026-04-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('projects', '0009_task_depends_on_task_is_critical_task_workflow_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='risks',
            field=models.ManyToManyField(blank=True, related_name='projects', to='plans.risk'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('DEVELOPER', 'Developer'), ('ANALYST', 'Analyst'), ('DESIGNER', 'Designer'), ('QA', 'QA Engineer')], default='DEVELOPER', max_length=30),
        ),
    ]
