# Generated by Django 6.0.4 on 2026-04-30 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('projects', '0010_project_risks_alter_projectmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='role_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='plans.projectrole'),
        ),
    ]
