# Generated by Django 6.0.4 on 2026-04-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtask',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='Вес задачи для расчета прогресса'),
        ),
        migrations.AddField(
            model_name='workflowtasktemplate',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='Вес задачи для расчета прогресса'),
        ),
    ]
