# Generated by Django 6.0.4 on 2026-04-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowtask_weight_workflowtasktemplate_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtask',
            name='estimated_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='workflowtasktemplate',
            name='estimated_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='workflowtasktemplate',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='workflowtasktemplate',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=20),
        ),
    ]
