# Generated by Django 6.0.4 on 2026-04-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflowtask_estimated_hours_workflowtask_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtask',
            name='auto_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='dependent_tasks', to='workflows.workflowtask'),
        ),
        migrations.AddField(
            model_name='workflowtasktemplate',
            name='auto_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowtasktemplate',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='dependent_templates', to='workflows.workflowtasktemplate'),
        ),
    ]
