# Generated by Django 6.0.4 on 2026-04-30 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectmember_role_ref'),
        ('workflows', '0004_workflowtask_auto_approve_workflowtask_depends_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtask',
            name='linked_wbs_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_tasks', to='projects.task'),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='transition_condition',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'type': 'approval_required', 'role': 'MANAGER'}"),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='wbs_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_tasks', to='projects.planningblock'),
        ),
    ]
