# Generated by Django 6.0.4 on 2026-05-01 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_workflowtask_linked_wbs_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
