# Generated by Django 6.0.4 on 2026-05-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_workflowtask_created_at_workflowtask_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtask',
            name='integration_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='integration_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowtasktemplate',
            name='integration_config',
            field=models.JSONField(blank=True, default=dict, help_text='Конфигурация payload/headers для вебхука'),
        ),
        migrations.AddField(
            model_name='workflowtasktemplate',
            name='integration_url',
            field=models.URLField(blank=True, help_text='URL для вызова вебхука (для INTEGRATION задач)', null=True),
        ),
    ]
