# Generated by Django 6.0.4 on 2026-05-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_add_integration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtask',
            name='checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workflowtasktemplate',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text='Список пунктов (строки)'),
        ),
    ]
