# Generated by Django 6.0.4 on 2026-05-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_workflowtask_checklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='ui_config',
            field=models.JSONField(blank=True, default=dict, help_text='Данные для UI (позиции узлов и т.д.)'),
        ),
    ]
