# Generated by Django 6.0.4 on 2026-05-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_workflowtemplate_ui_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtasktemplate',
            name='assigned_role',
            field=models.CharField(blank=True, help_text='Роль для назначения (например, MANAGER)', max_length=50, null=True),
        ),
    ]
