# Generated by Django 6.0.4 on 2026-04-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_employeeprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
