# Generated by Django 6.0.4 on 2026-04-30 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_employeeprofile_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='department',
        ),
    ]
