# Generated by Django 6.0.4 on 2026-05-01 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_remove_employeeprofile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название сертификата', max_length=255)),
                ('issuer', models.CharField(blank=True, help_text='Выдавшая организация', max_length=255)),
                ('credential_id', models.CharField(blank=True, help_text='Номер/ID сертификата', max_length=100)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Дата истечения (пусто = бессрочный)', null=True)),
                ('certificate_url', models.URLField(blank=True, help_text='Ссылка на онлайн-верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='matching.employeeprofile')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-issued_date'],
            },
        ),
    ]
