# Generated by Django 6.0.4 on 2026-05-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_add_employee_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID чата в Telegram для уведомлений', max_length=100),
        ),
    ]
