# Generated by Django 6.0.4 on 2026-05-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_employeeprofile_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='notify_daily_digest',
            field=models.BooleanField(default=True, verbose_name='Ежедневный дайджест'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='notify_email',
            field=models.BooleanField(default=True, verbose_name='Уведомления по Email'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='notify_telegram',
            field=models.BooleanField(default=True, verbose_name='Уведомления в Telegram'),
        ),
    ]
