# Generated by Django 6.0.4 on 2026-05-02 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_employeeprofile_notify_daily_digest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VACATION', 'Отпуск'), ('SICK_LEAVE', 'Больничный'), ('UNPAID_LEAVE', 'За свой счет'), ('OTHER', 'Другое')], default='VACATION', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability', to='matching.employeeprofile')),
            ],
            options={
                'verbose_name': 'Недоступность сотрудника',
                'verbose_name_plural': 'Недоступность сотрудников',
                'ordering': ['-start_date'],
            },
        ),
    ]
